### ISSUE TITLE
The requested module './snippets/mapboxgl-89106e6563064742/mapbox-gl.js' does not provide an export named 'Map'

### ISSUE THREAD

**Issue by LiamGallagher737** [yukinarit/mapbox-gl-rs#1]
Hi, I am trying to display a map in a [`perseus`](https://github.com/framesurge/perseus) app. I have copied the [`mapbox-gl.js`](https://github.com/yukinarit/mapbox-gl-rs/blob/main/mapbox-gl.js) into my project and mapped it to `./snippets/mapboxgl-89106e6563064742/mapbox-gl.js`.

When I visit the page with the map on it I get the following error.

```js
Uncaught SyntaxError: The requested module './snippets/mapboxgl-89106e6563064742/mapbox-gl.js' does not provide an export named 'Map' (at bundle.js:1:10)
```

The pages setup is as follows.

When the page loads I run the following code (only in browser not SSR)
```rs
let map_state = state.map_state.get().as_ref().to_owned();
let options = MapOptions::new(
    "pk.eyJ1IjoibGlhbTczNyIsImEiOiJjbDZpdzh1cGgweDc2M2RvMndja2xlOHFzIn0.b9nPCIMzEkN6qWYsSQMoog".into(),
    "map".into(),
).center(LatLng {
    lat: map_state.lat,
    lng: map_state.lng,
}).zoom(map_state.zoom);
let mut map = MapFactory::new(options).unwrap();
map.set_listener(MapListener);
```

And add the following html to the page

```html
<div id="map" class="w-screen h-screen"></div>
```

In the head I added the Mapbox css with the following
```html
<link rel = "stylesheet" href = "https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css" />
```

Currently the map listener is empty, issue still occurs without a listener
```rs
struct MapListener;
impl MapEventListner for MapListener { }
```

When I visit the page, the page is blank and I get this in the dev tools

![image](https://user-images.githubusercontent.com/86995276/200716473-9f728007-9109-4d5f-b0a4-184692f268e9.png)

And when I open bundle.js in the dev tools I see the following

![image](https://user-images.githubusercontent.com/86995276/200716581-007441cb-0192-4646-839b-4367aa4425ad.png)

I'm not sure what to do now so if someone could help me fix this it would be greatly appreciated

**Comment by yukinarit** [comment]
Hi @LiamGallagher737 

Thank you for using mapbox-gl-rs! Maybe you're the very first user 😄 

Your issue was the trickiest part that I struggled during the development of this crate. Since I am new to Perseus, Let me explain how I resolved this issue for [Yew](https://github.com/yewstack/yew).

---

First of all, `mapbox-gl.js` is originally built as [UMD (Universal Module Definition)](https://github.com/umdjs/umd). I modified [their build script](https://github.com/mapbox/mapbox-gl-js/blob/main/rollup.config.js) to produce [ESM](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) version of `mapbox-gl.js`, because Yew (and Perseus) based webapps use ESM. The ESM version of mapbox-gl.js is in [the repo](https://github.com/yukinarit/mapbox-gl-rs/blob/main/mapbox-gl.js).

But still Yew webapp fails to import from ESM `mapbox-gl.js` like this issue, so I decided to use Webpack to rebundle the JS code + WASM + ESM `mapbox-gl.js`.

As an example, please take a look at [examples/set-data/package.json](https://github.com/yukinarit/mapbox-gl-rs/blob/246f7a0513cd149af41c833a99639783c6ef860a/examples/set-data/package.json#L5). 

```
trunk build && ./app.sh && webpack
```

1. `trunk build` compiles Rust into JavaScript + WASM under `dist` directory. 

```
$ find dist
find dist
dist
dist/snippets
dist/snippets/mapboxgl-e9c4241defdbcb5b
dist/snippets/mapboxgl-e9c4241defdbcb5b/mapbox-gl.js
dist/index.html
dist/set-data-d62ad216ab35b679.js
dist/set-data-d62ad216ab35b679_bg.wasm
```

2. [app.sh](https://github.com/yukinarit/mapbox-gl-rs/blob/246f7a0513cd149af41c833a99639783c6ef860a/examples/set-data/app.sh) generates `dist/app.js` and `app/index.html` as follows. `dist/app.js` will call `init` function from the JS produced by `trunk build` `app/index.html` is a static HTML file to serve the app.

```javascript
$ cat dist/app.js
import init from './set-data-d62ad216ab35b679'
init()
```

```html
cat app/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>App</title>
    <link href='https://api.mapbox.com/mapbox-gl-js/v2.10.0/mapbox-gl.css' rel='stylesheet' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script defer src="main.js"></script>
  </head>
  <body style="margin: 0; padding: 0">
  </body>
</html>
```

3. Finally, bundle the javascript files produced in steps 2 and 3 using Webpack. Webpack config is like this
```javascript
const path = require('path');

module.exports = {
    mode: 'development',
    entry: './dist/app.js',
    resolve: {
          extensions: ['.js', '.wasm'],
        },
    output: {
          path: path.resolve(__dirname, 'app'),
    },
    experiments: {
      syncWebAssembly: true,
    },
}
```

`webpack` command produces the final scripts as below
```
$ find app
app/index.html
app/823e3bc961ef5df2746f.wasm
app/main.js
```

Maybe there should be a better way. I need to learn more about Webpack and [Trunk](https://github.com/thedodd/trunk). But this way worked at least for me. Could you please try? Hope this will help solve your issue.

**Comment by yukinarit** [comment]
Hi @LiamGallagher737!

I finally figured out how to make mapbox-gl-rs work without Webpack! Please use the new `0.1.0` and follow the [usage](https://github.com/yukinarit/mapbox-gl-rs#usage). Now it should be a lot easier than before. 

I couldn't try Perseus + `mapbox-gl-rs`. It would be helpful if you could find a way to do that and possibly contribute an example code. Thank you 🙂
